### PR TITLE
Change in address

### PR DESCRIPTION
**Pull request by smgom**

### CODE REVIEW

**Comment by alovak** [comment]
@smgom thanks!

Let's refactor it a bit. At least we can remove duplication. As example:

```php
$billing_address = getAddress($order->getBillingAddress());
$shipping_address = getAddress($order->getShippingAddress());
```

**Comment by smgom** [comment]
Sure ok

**Comment by smgom** [comment]
Hi but these are two different things and being used.

**Comment by alovak** [comment]
Why they are different?

**Pull request closed without merging**
